name: 'Build Java Application'
description: 'Github action to build java apps'
author: 'Raditya Saskara'

outputs:
  running:
    description: 'Boolean value indicating if the action was running'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
        shell: bash
