name: "Build Java Application"
description: "Github action to build java apps"
author: "Raditya Saskara"

inputs:
  java-version:  
    description: 'java version'
    default: '11'
  app-version:
    description: 'apps version'
    required: true
    default: '1'
  app-name:
    description: 'apps version'
    required: true
  docker-container:
    description: 'create a docker image'
    default: true


outputs:
  running:
    description: "Boolean value indicating if the action was running"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: "11"
        distribution: "adopt"
        cache: maven
    - run: mvn --batch-mode --update-snapshots verify
      shell: bash
    - run: mkdir ${{ inputs.app-name }} && cp target/*.jar ${{ inputs.app-name }}/${{ inputs.app-name }}x${{ inputs.app-version }}.jar
      shell: bash
    - run: echo ${{ inputs.app-name }}x${{ inputs.app-version }}
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: ${{ inputs.app-name }}
    - run: |
        if echo ${{ inputs.docker-container }} | grep -c "true"
            then
              echo "FROM openjdk:11-jre-slim \nCOPY ${{ inputs.app-name }}/${{ inputs.app-name }}x${{ inputs.app-version }}.jar /usr/local/lib/ \nEXPOSE 8080 \nENTRYPOINT ["java","-jar","/usr/local/lib/${{ inputs.app-name }}x${{ inputs.app-version }}.jar"]" > Dockerfile
        fi
      shell: bash
    - run: |
        if echo ${{ inputs.docker-container }} | grep -c "true"
            then cat Dockerfile
        fi
      shell: bash
    
    # With Buildah
    - uses: redhat-actions/buildah-build@v2
      with:
        base-image: docker.io/fabric8/java-alpine-openjdk11-jre
        image: ${{ inputs.app-name }}
        tags: ${{ inputs.app-version }}
        content: ${{ inputs.app-name }}/${{ inputs.app-name }}x${{ inputs.app-version }}.jar
        entrypoint: java -jar ${{ inputs.app-name }}x${{ inputs.app-version }}.jar
        port: 8080
