name: "Build Java Application"
on:
  workflow_call:
    inputs:
      java-version:  
        description: 'java version'
        type: string
        default: '11'
      app-version:
        description: 'apps version'
        type: string
        required: true
        default: '1'
      app-name:
        description: 'apps version'
        type: string
        required: true
    secrets:
      gcloud-key:
        required: true

jobs:
  build_job:
    name: Build java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven
      - run: mvn --batch-mode --update-snapshots verify
        shell: bash
      - run: mkdir ${{ inputs.app-name }} && cp target/*.jar ${{ inputs.app-name }}/${{ inputs.app-name }}x${{ inputs.app-version }}.jar
        shell: bash
      - run: echo ${{ inputs.app-name }}x${{ inputs.app-version }}
        shell: bash
      - run: |
          echo "FROM openjdk:11-jre-slim 
          COPY ${{ inputs.app-name }}/${{ inputs.app-name }}x${{ inputs.app-version }}.jar /usr/local/lib/ 
          EXPOSE 8080 
          ENTRYPOINT ["java","-jar","/usr/local/lib/${{ inputs.app-name }}x${{ inputs.app-version }}.jar"]" > Dockerfile
        shell: bash
      - run: |
          cat Dockerfile
        shell: bash
      
      # Push to GCR
      - name: Login to gcloud registry
        id: gcloud
        uses: elgohr/gcloud-login-action@master
        with:
          account_key: ${{ secrets.gcloud-key }}
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ inputs.app-name }}
          username: ${{ steps.gcloud.outputs.username }}
          password: ${{ steps.gcloud.outputs.password }}
          dockerfile: Dockerfile
          tags: ${{ inputs.app-version }}
          registry: asia.gcr.io/rise-prod-327008
