name: "Build Java Application"
on:
  workflow_call:
    inputs:
      java-version:  
        description: 'java version'
        type: string
        default: '11'
        required: false
      volumes:
        description: 'volumes'
        type: string
        required: true

jobs:
  build_job:
    nvame: Test
    runs-on: ubuntu-latest
    steps:
      - name: Create list of modified files
        id: modified_files_list
        uses: lucaspinheirogit/list-from-string-array-action@v1.4.3
        with:
          stringArray: ${{ inputs.volumes }}
      - container:
          image: adocker://nginx:latest
          volumes: ${{ steps.modified_files_list.outputs.stringList }}
